version: "3.2"

services:
  proxy:
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      NGINX_PORT: ${PORT}
    expose:
      - ${PORT}
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    restart: unless-stopped

  app:
    image: listmonk/listmonk:latest
    expose:
      - 9000
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
    restart: unless-stopped

  db:
    image: postgres:11
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

volumes:
  listmonk-data:

networks:
  default:
    external:
      name: nginx-proxy
