version: "3.2"

services:
  proxy:
    build: .
    environment:
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${EMAIL}
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      NGINX_PORT: ${PORT}
    expose:
      - ${PORT}
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - app
    restart: unless-stopped

  app:
    image: listmonk/listmonk:latest
    expose:
      - ${APP_PORT}
    depends_on:
      - db
    environment:
      LISTMONK_app__address: ${LISTMONK_app__address}
      LISTMONK_app__root: ${LISTMONK_app__root}
      LISTMONK_app__logo_url: ${LISTMONK_app__logo_url}
      LISTMONK_app__favicon_url: ${LISTMONK_app__favicon_url}
      LISTMONK_app__from_email: ${LISTMONK_app__from_email}
      LISTMONK_app__notify_emails: ["francoisromain@gmail.com"]
      LISTMONK_db__host: ${LISTMONK_db__host}
      LISTMONK_db__port: ${LISTMONK_db__port}
      LISTMONK_db__user: ${LISTMONK_db__user}
      LISTMONK_db__password: ${LISTMONK_db__password}
      LISTMONK_db__database: ${LISTMONK_db__database}
      LISTMONK_smtp__my0__enable: ${LISTMONK_smtp__my0__enable}
      LISTMONK_smtp__my0__host: ${LISTMONK_smtp__my0__host}
      LISTMONK_smtp__my0__port: ${LISTMONK_smtp__my0__port}
      LISTMONK_smtp__my0__auth_protocol: ${LISTMONK_smtp__my0__auth_protocol}
      LISTMONK_smtp__my0__username: ${LISTMONK_smtp__my0__username}
      LISTMONK_smtp__my0__password: ${LISTMONK_smtp__my0__password}
    restart: unless-stopped

  db:
    image: postgres:12
    expose:
      - ${LISTMONK_db__port}
    environment:
      - POSTGRES_PASSWORD=${LISTMONK_db__password}
      - POSTGRES_USER=${LISTMONK_db__user}
      - POSTGRES_DB=${LISTMONK_db__database}
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

volumes:
  listmonk-data:

networks:
  default:
    external:
      name: nginx-proxy
