version: "3.2"

services:
  proxy:
    build: .
    environment:
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${EMAIL}
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      NGINX_PORT: ${PORT}
      APP_PORT: ${APP_PORT}
    expose:
      - ${PORT}
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - app
    restart: unless-stopped

  app:
    image: listmonk/listmonk:latest
    expose:
      - ${APP_PORT}
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${LISTMONK_db__database}
      POSTGRES_USER: ${LISTMONK_db__user}
      POSTGRES_PASSWORD: ${LISTMONK_db__password}
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

volumes:
  listmonk-data:

networks:
  default:
    external:
      name: nginx-proxy
