version: "3"

services:
  app:
    build: .
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${EMAIL}
      NGINX_PORT: ${PORT}
    expose:
      - ${PORT}
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
